services:
  mongodb:
    image: mongo:7.0
    container_name: curve_mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: curve_db
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network

  app:
    build: .
    container_name: curve_app
    restart: no
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/curve_db?authSource=admin
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app_network

volumes:
  mongodb_data:

networks:
  app_network:
    driver: bridge